version: '3.3'
services:
  back:
    image: ${PROJ_NAME}:latest
    container_name: ${PROJ_NAME}
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back/app:/home/app
      # - /home/app/node_modules
    ports:
      - ${DEV_PORT}:3000
      - ${PROD_PORT}:5000
    tty: true
